### ISSUE TITLE
Unknown error when a transaction is signed with the U2F way.

### ISSUE THREAD

**Issue by yharvey** [ZondaX/ledger-matrix-js#2]
Unknown error when a transaction is signed with the U2F way.

**Comment by jleni** [comment]
could you provide more info?
1) Steps to reproduce the issue
2) ideally the transaction or source code that shows the issue?

**Comment by yharvey** [comment]
sourve is ledger-matrix-js
step 1.chose U2F
step 2.press the sign example1 tx
step 3. sign the transaction with ledger.
then the issue will reproduce.
![image](https://user-images.githubusercontent.com/7820961/64239377-b8f6b080-cf32-11e9-9037-01f9fdaba81a.png)

**Comment by yharvey** [comment]
if i press two button on ledger to skip view the transaction, it can sign success. but  when i press right button to view all info of the transaction , then select sign menu , unknown error happened  again.
